#!bin/bash

# Install MongoDB Shell
wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
apt-get update
apt-get install -y mongodb-mongosh

# Drop database
mongosh "${DATABASE_CONNECTION_STRING}/${HEROKU_APP_NAME}-database" --eval "db.dropDatabase()"