name: CI
on:
    pull_request:
    push:
        branches:
            - development
            - master
jobs:
    macos-test:
        name: macos-test
        runs-on: macos-12
        steps:
        - uses: actions/checkout@v3
        - name: docker_installation
          run: brew install docker
        - name: container_runtime_setup
          run: colima start
        - name: database_setup
          run: docker run --name mongodb -d -p 27017:27017 mongo
        - name: test
          run: swift test
    ubuntu-test:
        name: ubuntu-test
        runs-on: ubuntu-20.04
        steps:
        - uses: actions/checkout@v3
#        - name: swift_installation
#          uses: swift-actions/setup-swift@v1.18.0
#          with:
#            swift-version: '5.5'
        - name: database_setup
          run: docker run --name mongodb -d -p 27017:27017 mongo
        - name: test
          run: swift test
