name: Repository Maintenance
on:
    pull_request:
        types:
        - closed
jobs:
    review environment and deployments teardown:
        name: review environment and deployments teardown
        runs-on: ubuntu-latest
        steps:
        - uses: strumwolf/delete-deployment-environment@v2
          with:
            token: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN_TVBE_MAINTENANCE }}
            environment: review-tvbe-pr-${{ github.event.number }}
