name: Repository Maintenance
on:
    pull_request:
        types:
        - closed
jobs:
    review_environment_and_deployments_teardown:
        name: Review Environment and Deployments Teardown
        runs-on: ubuntu-latest
        steps:
        - uses: strumwolf/delete-deployment-environment@v2
          with:
            token: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN_TVBE_MAINTENANCE }}
            environment: review-tvbe-pr-${{ github.event.number }}
