name: ci
on:
    pull_request:
    push:
        branches:
            - development
            - master
jobs:
    test:
        name: test
        runs-on: macos-12
        steps:
        - uses: actions/checkout@v3
        - name: colima_start
          run: colima start
        - name: database_setup
          run: docker run --name mongodb -d -p 27017:27017 mongo
        - name: test
          run: swift test
