name: ci
on:
    pull_request:
    push:
        branches:
            - development
            - master
jobs:
    test:
        name: test
        runs-on: macos-12
        steps:
        - uses: actions/checkout@v3
        - name: database_setup
          uses: supercharge/mongodb-github-action@1.8.0
        - name: test
          run: swift test
