name: test
on:
    pull_request:
    push:
        branches:
            - development
            - master
jobs:
    build:
        runs-on: macos-12
        steps:
        - uses: actions/checkout@v3
        - name: test
          run: swift test
